[package]
name = "zerochecker"
version = "0.1.0"
authors = ["Carl Sandrock <carl.sandrock@up.ac.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
